def exception():
    raise RuntimeError()


exception()
